<?php
/**
 * Mageplaza_BetterBlog extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category       Mageplaza
 * @package        Mageplaza_BetterBlog
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Post view template
 *
 * @category    Mageplaza
 * @package     Mageplaza_BetterBlog
 * @author      Sam
 *
 *
 * ===================================================================================
 *   INCLUDE THIS EXTENSION TO YOUR THEMES, PLEASE CONTACT ME AT harrytpps@gmail.com
 * ===================================================================================
 *
 *
 */
?>
<?php $_post = $this->getCurrentPost(); ?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

    <div class="page-title post-title">
        <h1><?php echo $this->escapeHtml($_post->getPostTitle()); ?></h1>
    </div>
    <div class="post-view">

        <div class="mc-post-info">
            <?php echo $this->__('Posted on'); ?> <?php echo Mage::helper('core')->formatDate($_post->getCreatedAt(), 'medium', false) ?>
            |
            <?php echo $this->__('Posted in'); ?> <?php echo $_post->getPostCategoryHtml(); ?> |
            <?php if (Mage::helper('mageplaza_betterblog')->canShowCommentCount()) echo Mage::helper('mageplaza_betterblog')->formatCommentCount($_post->getCommentCount()); ?>
        </div>

        <div class="post-post_excerpt">
            <?php echo $_post->getPostExcerpt(); ?>

        </div>
        <br>

        <div class="post-image">
            <?php if ($_post->getImage()) : ?>
                <a href="<?php echo $this->escapeUrl($_post->getPostUrl()); ?>" title="<?php echo $this->escapeHtml($_post->getPostTitle()); ?>">
                    <img src="<?php echo Mage::helper('mageplaza_betterblog/post_image')->init($_post, 'image'); ?>"
                         alt="<?php echo $this->escapeHtml($_post->getPostTitle()); ?>"/>
                </a>
            <?php endif; ?>
        </div>


        <div class="post-post_content">
            <?php echo $_post->getPostContent(); ?>
        </div>

        <div class="post-products post-post_content">
            <?php $relatedProducts = $_post->getSelectedProductsCollection(); ?>
            <?php if ($relatedProducts): ?>
                <h2><?php echo $this->__('Products'); ?></h2>
                <ul>
                    <?php foreach ($relatedProducts as $_product): ?>
                        <li>
                            <a href="<?php echo $this->escapeUrl($_product->getProductUrl()) ?>" title="<?php echo $this->__('Buy'); ?> <?php echo $this->escapeHtml($_product->getName()); ?>">
                                <img class="img-responsive" src="<?php echo $this->helper('catalog/image')->init($_product,'small_image')->resize(350); ?>" border="0" /> <br class="clear">
                                <button type="button" title="<?php echo $this->__('Buy'); ?> <?php echo $this->escapeHtml($_product->getName()); ?>" class="button btn-cart"><span><span><?php echo $this->__('Buy'); ?> <?php echo $this->escapeHtml($_product->getName()); ?></span></span></button>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </div>

    </div>


    <div class="post-same-topics post-list">
        <?php $similarPosts = $this->getPostTopics(); ?>
        <?php if ($similarPosts): ?>
            <h2><?php echo $this->__('Topic'); ?>: <?php echo $this->escapeHtml($this->getTopicLabel()); ?></h2>
            <ul>
                <?php foreach ($similarPosts as $post): ?>
                    <li>
                        <a href="<?php echo $this->escapeUrl($post->getPostUrl()) ?>"><?php echo $this->escapeHtml($post->getPostTitle()); ?></a>
                    </li>
                <?php endforeach; ?>

            </ul>

        <?php endif; ?>

    </div>

<?php if ($this->canShowPostSameCategory()): ?>
    <div class="post-list posts-in-category">
        <?php $posts = $this->getPostsInCategory(); ?>
        <?php if ($posts && $posts->count()): ?>
            <h2><?php echo $this->__('Category'); ?>: <?php echo $this->escapeHtml($this->getCategoryName()); ?></h2>
            <ul>
                <?php foreach ($posts as $post): ?>
                    <li>
                        <a href="<?php echo $this->escapeUrl($post->getPostUrl()) ?>"><?php echo $this->escapeHtml($post->getPostTitle()); ?></a>
                    </li>
                <?php endforeach; ?>

            </ul>
        <?php endif; ?>
    </div>

<?php endif; ?>